export * from './main/main'
export * from './registration/registration'
export * from './hotel/hotel-page'
export * from './user-account/user-account'
export * from './contacts/contacts'
export * from './admin-page/admin-page'
