export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	SET_BOOKING: 'SET_BOOKING',
	ADD_BOOKING: 'ADD_BOOKING',
	CANCEL_BOOKING: 'CANCEL_BOOKING',
	SET_HOTEL_DATA: 'SET_HOTEL_DATA',
	RESET_HOTEL_DATA: 'RESET_HOTEL_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	SET_ROOM: 'SET_ROOM',
	ADD_ROOM: 'ADD_ROOM',
	REMOVE_ROOM: 'REMOVE_ROOM',
	LOGOUT: 'LOGOUT',
};
